---
title: "Demographic data wrangling"
author: "Bo Chen"
date: "5/12/2021"
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
---


```{r message=FALSE}
knitr::opts_chunk$set(error = TRUE)
library(pacman)
p_load(tidyverse,stringr,COVID19,MASS,knitr,magrittr)
#remotes::install_cran("tidyverse")
#library(tidyverse)
```


# Read the.csv files

```{r message=FALSE}
QuickFacts1  <- read_csv(file="QuickFacts Feb-11-2021 -1.csv")
QuickFacts2  <- read_csv(file="QuickFacts Feb-11-2021 -2.csv")
QuickFacts3  <- read_csv(file="QuickFacts Feb-11-2021 -3.csv")
QuickFacts4  <- read_csv(file="QuickFacts Feb-11-2021 -4.csv")
QuickFacts5  <- read_csv(file="QuickFacts Feb-11-2021 -5.csv")
QuickFacts6  <- read_csv(file="QuickFacts Feb-11-2021 -6.csv")
QuickFacts7  <- read_csv(file="QuickFacts Feb-11-2021 -7.csv")
QuickFacts8  <- read_csv(file="QuickFacts Feb-11-2021 -8.csv")
QuickFacts9  <- read_csv(file="QuickFacts Feb-11-2021 -9.csv")
QuickFacts10  <- read_csv(file="QuickFacts Feb-11-2021 -10.csv")
```

# Check the head() of the data.frame that is loaded.

```{r}
QuickFacts1 <- QuickFacts1[c(31,33,45,61),c(1,3,5,7,9,11,13)]
head(QuickFacts1)
```
# Take subsets of the data.frames

```{r}
QuickFacts2 <- QuickFacts2[c(31,33,45,61),c(3,5,7,9,11,13)]
QuickFacts3 <- QuickFacts3[c(31,33,45,61),c(3,5,7,9,11,13)]
QuickFacts4 <- QuickFacts4[c(31,33,45,61),c(3,5,7,9,11,13)]
QuickFacts5 <- QuickFacts5[c(31,33,45,61),c(3,5,7,9,11,13)]
QuickFacts6 <- QuickFacts6[c(31,33,45,61),c(3,5,7,9,11,13)]
QuickFacts7 <- QuickFacts7[c(31,33,45,61),c(3,5,7,9,11,13)]
QuickFacts8 <- QuickFacts8[c(31,33,45,61),c(3,5,7,9,11,13)]
QuickFacts9 <- QuickFacts9[c(31,33,45,61),c(3,5,7,9,11,13)]
QuickFacts10 <- QuickFacts10[c(31,33,45,61),c(3,5,7,9)]
```

# Reshaping Data
```{r}
QuickFacts1 %>% gather(country,var,2:7) %>% spread(Fact, var)
```

# Combine demographic data

```{r}
demo_ca <- cbind(QuickFacts1,QuickFacts2,QuickFacts3,QuickFacts4,QuickFacts5,QuickFacts6,
                 QuickFacts7,QuickFacts8,QuickFacts9,QuickFacts10)

demo_ca <- demo_ca %>% gather(country,var,2:59) %>% spread(Fact, var)

head(demo_ca)

oldnames = c("Bachelor's degree or higher, percent of persons age 25 years+, 2015-2019",
             "Households with a broadband Internet subscription, percent, 2015-2019",
             "Land area in square miles, 2010",
             "Median household income (in 2019 dollars), 2015-2019")
newnames = c("education","internet","area","income")

demo_ca_rename <- demo_ca %>% rename_at(all_of(oldnames), ~ newnames)
# view(demo_ca_rename)
head(demo_ca_rename)
```
# Data Wrangling

```{r}
demo_ca_rename$education=str_sub(demo_ca_rename$education,1,4)

demo_ca_rename$internet=str_sub(demo_ca_rename$internet,1,4)

demo_ca_rename$area=gsub(",","",demo_ca_rename$area)

demo_ca_rename$income=gsub("[\\$,]",'', demo_ca_rename$income)

ca_county <- demo_ca_rename %>% dplyr::select(country)
ca_county

demo_ca_rename1 <- demo_ca_rename %>% dplyr::select(-country) %>% mutate_if(is.character,as.numeric)
demo_ca_rename1

demo_ca_county <- cbind(ca_county, demo_ca_rename1)
demo_ca_county

demo_ca_county <- demo_ca_county %>% mutate(education=education*0.01, internet=internet*0.01)
demo_ca_county
view(demo_ca_county)
```

